//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALCOHOL_COLLECTS_MONEY
    {
        public double ALCOHOL_COLLECTS_MONEY___QUANTITY { get; set; }
        public Nullable<System.DateTime> DATE_ID { get; set; }
        public string TYPE_OF_WINE___ID { get; set; }
        public long ALCOHOL_COLLECTS_MONEY___PRICE { get; set; }
        public string ALCOHOL_COLLECTS_MONEY___ID { get; set; }
    
        public virtual DATE DATE { get; set; }
        public virtual TYPE_OF_WINE TYPE_OF_WINE { get; set; }
    }
}
