//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALCOHOL_COLLECTS_MONEY
    {
        [Required(ErrorMessage = "Số lít bán được là bắt buộc.")]
        [Display(Name = "Số lít bán được")]
        [Range(1,int.MaxValue, ErrorMessage = "Giá trị phải lớn hơn 0")]
        public double ALCOHOL_COLLECTS_MONEY_QUANTITY { get; set; }

        [Required(ErrorMessage = "Ngày bán là bắt buộc.")]
        [Display(Name = "Ngày bán")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATE_ID { get; set; }

        [Required(ErrorMessage = "Loại rượu là bắt buộc.")]
        [Display(Name = "Loại rượu")]
        public Nullable<int> TYPE_OF_WINE_ID { get; set; }

        [Required(ErrorMessage = "Số tiền là bắt buộc.")]
        [Display(Name = "Số tiền thu được")]
        public long ALCOHOL_COLLECTS_MONEY_PRICE { get; set; }

        [Required]
        [Display(Name = "Mã")]
        public string ALCOHOL_COLLECTS_MONEY_ID { get; set; }
    
        public virtual DATE DATE { get; set; }
        public virtual TYPE_OF_WINE TYPE_OF_WINE { get; set; }
    }
}
