//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALCOHOL_SPENDING_MONEY
    {
        [Required]
        public long ALCOHOL_SPENDING_MONEY_ID { get; set; }
        [Required(ErrorMessage = "Ngày là bắt buộc")]
        [Display(Name = "Ngày")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DATE_ID { get; set; }

        [Required(ErrorMessage = "Nội dung chi là bắt buộc")]
        [Display(Name = "Nội dung chi")]
        [StringLength(200, ErrorMessage = "Độ dài tối đa là 200 ký tự")]
        public string ALCOHOL_SPENDING_MONEY_CONTENT { get; set; }
        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng là bắt buộc")]
        [Range(1, int.MaxValue, ErrorMessage = "Số lượng là một số nguyên lớn hơn 0")]
        public double ALCOHOL_SPENDING_MONEY_QUANTITY { get; set; }

        [Display(Name = "Ghi chú")]
        [Required(ErrorMessage = "ghi chú là bắt buộc")]
        [StringLength(200, ErrorMessage = "Độ dài tối đa là 200 ký tự")] 
        public string ALCOHOL_SPENDING_MONEY_NOTE { get; set; }


        public virtual DATE DATE { get; set; }
    }
}
