//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALCOHOL_SPENDING_MONEY
    {
        [Required]
        [Display(Name = "Mã")]
        public long ALCOHOL_SPENDING_MONEY_ID { get; set; }

        [Required(ErrorMessage = "Ngày chi là bắt buộc.")]
        [Display(Name = "Ngày chi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATE_ID { get; set; }

        [Required(ErrorMessage = "Nội dung chi là bắt buộc.")]
        [Display(Name = "Nội dung chi")]
        //[StringLength(0, MinimumLength = 200, ErrorMessage = "Trường nội dung chi phải có ít nhất 1 ký tự và không vượt quá 200 ký tự.")]
        public string ALCOHOL_SPENDING_MONEY_CONTENT { get; set; }

        [Required(ErrorMessage = "Số lượng là bắt buộc.")]
        [Display(Name = "Số lượng")]
        [Range(1, int.MaxValue, ErrorMessage = "Giá trị phải lớn hơn 0")]
        public double ALCOHOL_SPENDING_MONEY_QUANTITY { get; set; }


        [Display(Name = "Ghi chú")]
      //  [StringLength(0, MinimumLength = 200, ErrorMessage = "Trường ghi chú phải có ít nhất 1 ký tự và không vượt quá 200 ký tự.")]
        public string ALCOHOL_SPENDING_MONEY_NOTE { get; set; }


        [Required(ErrorMessage = "Số tiền chi.")]
        [Display(Name = "Số tiền chi")]
        public long ALCOHOL_SPENDING_MONEY_PRICE { get; set; }

        public virtual DATE DATE { get; set; }
    }
}
