//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALCOHOL_SPENDING_MONEY
    {
        public long ALCOHOL_SPENDING_MONEY_ID { get; set; }
        public Nullable<System.DateTime> DATE_ID { get; set; }
        public string ALCOHOL_SPENDING_MONEY_CONTENT { get; set; }
        public double ALCOHOL_SPENDING_MONEY_QUANTITY { get; set; }
        public string ALCOHOL_SPENDING_MONEY_NOTE { get; set; }
        public long ALCOHOL_SPENDING_MONEY_PRICE { get; set; }
    
        public virtual DATE DATE { get; set; }
    }
}
