//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COLLECT_MONEY
    {
        [Required(ErrorMessage = "Mã")]
        public long CLMN_ID { get; set; }

        [Required(ErrorMessage = "Trường Ngày là bắt buộc.")]
        [Display(Name = "Ngày")]
        [DataType(DataType.Date, ErrorMessage = "Trường Ngày phải là một ngày hợp lệ.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATE_ID { get; set; }


        [Display(Name = "Menu ID")]
        [Required(ErrorMessage = "Menu ID là bắt buộc")]
        public Nullable<int> MN_ID { get; set; }


        [Required(ErrorMessage = "Trường Số lượng là bắt buộc.")]
        [Display(Name = "Số lượng")]
        [Range(0, int.MaxValue, ErrorMessage = "Trường Số lượng phải là một số không âm.")]
        public int CLMN_QUANLITY { get; set; }

        [Required(ErrorMessage = "Trường Giá cả là bắt buộc.")]
        [Display(Name = "Giá cả")]
        [Range(0, long.MaxValue, ErrorMessage = "Trường Giá cả phải là một số không âm.")]
        public long CLMN_PRICE { get; set; }

        [Display(Name = "Ghi chú")]
        [StringLength(150, ErrorMessage = "Trường Ghi chú không được vượt quá 150 ký tự.")]
        public string CLMN_NOTE { get; set; }

        public virtual DATE DATE { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
