//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.COLLECT_MONEY = new HashSet<COLLECT_MONEY>();
        }
        [Required]
        [Display(Name = "Mã menu")]
        public int MN_ID { get; set; }

        [Display(Name = "Tên đồ uống")]
        [Required(ErrorMessage ="Tên đồ uống là bắt buộc")]
        [StringLength(200, ErrorMessage = "Độ dài tối đa là 200 ký tự")]
        public string MN_PRODUCTNAME { get; set; }

        [Required(ErrorMessage = "Giá uống là bắt buộc")]
        [Range(0, long.MaxValue, ErrorMessage = "Giá phải là một số nguyên không âm.")]
        public Nullable<long> MN_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECT_MONEY> COLLECT_MONEY { get; set; }
    }
}
