//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SPENDING_MONEY
    {
        [Required(ErrorMessage = "Trường  chi Tiêu là bắt buộc.")]
        [Display(Name = "ID Chi Tiêu")]
        public long SPENDING_ID { get; set; }

        [Display(Name = "Ngày")]
        [DataType(DataType.Date, ErrorMessage = "Trường ngày phải là một ngày hợp lệ.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATE { get; set; }


        [Required(ErrorMessage = "Trường nội dung chi tiêu là bắt buộc.")]
        [Display(Name = "Nội dung chi tiêu")]
        [StringLength(200, ErrorMessage = "Trường nội dung chi tiêu không được vượt quá 200 ký tự.")]
        public string SPENDING_CONTENT { get; set; }

        [Required(ErrorMessage = "Trường số lượng là bắt buộc.")]
        [Display(Name = "Số lượng")]
        [Range(0, int.MaxValue, ErrorMessage = "Trường số lượng phải là một số không âm.")]
        public int SPENDING_QUANLITY { get; set; }


        [Required(ErrorMessage = "Trường giá trị là bắt buộc.")]
        [Display(Name = "giá")]
        [Range(0, long.MaxValue, ErrorMessage = "Trường {0} phải là một số không âm.")]
        public long SPENDING_PRICE { get; set; }

        [Display(Name = "Ghi chú")]
        [StringLength(200, ErrorMessage = "Trường {0} không được vượt quá {1} ký tự.")]
        public string SPENDING_NOTE { get; set; }


    
        public virtual DATE DATE1 { get; set; }
    }
}
