//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPENDING_MONEY
    {
        public long SPENDING_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string SPENDING_CONTENT { get; set; }
        public int SPENDING_QUANLITY { get; set; }
        public long SPENDING_PRICE { get; set; }
        public string SPENDING_NOTE { get; set; }
    
        public virtual DATE DATE1 { get; set; }
    }
}
