//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TYPE_OF_WINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPE_OF_WINE()
        {
            this.ALCOHOL_COLLECTS_MONEY = new HashSet<ALCOHOL_COLLECTS_MONEY>();
        }

        [Display(Name = "Mã")]
        [Required]
        public int TYPE_OF_WINE_ID { get; set; }

        [Display(Name = "Tên rượu")]
        [Required(ErrorMessage = "Tên rượu là bắt buộc")]
        [StringLength(150, ErrorMessage = "Độ dài tối đa là 150 ký tự")]
        public string TYPE_OF_WINE_NAME { get; set; }

        [Display(Name = "Giá của 1 lít rượu")]
        [Required(ErrorMessage = "Giá rượu là bắt buộc")]
        [Range(0, long.MaxValue, ErrorMessage = "Giá phải là một số nguyên không âm.")]
        public long TYPE_OF_WINE_PRICE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALCOHOL_COLLECTS_MONEY> ALCOHOL_COLLECTS_MONEY { get; set; }
    }
}
