//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoffeeWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TYPE_OF_WINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPE_OF_WINE()
        {
            this.ALCOHOL_COLLECTS_MONEY = new HashSet<ALCOHOL_COLLECTS_MONEY>();
        }

        [Required(ErrorMessage = "Trường {0} là bắt buộc.")]
        [Display(Name = "ID Loại Rượu")]
        public int TYPE_OF_WINE_ID { get; set; }

        [Required(ErrorMessage = "Trường {0} là bắt buộc.")]
        [Display(Name = "Tên Loại Rượu")]
        [StringLength(100, ErrorMessage = "Trường {0} không được vượt quá {1} ký tự.")]
        public string TYPE_OF_WINE_NAME { get; set; }

        [Required(ErrorMessage = "Trường {0} là bắt buộc.")]
        [Display(Name = "Giá Loại Rượu")]
        [Range(0, long.MaxValue, ErrorMessage = "Trường {0} phải là một số không âm.")]
        public long TYPE_OF_WINE_PRICE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALCOHOL_COLLECTS_MONEY> ALCOHOL_COLLECTS_MONEY { get; set; }
    }
}
